### ISSUE TITLE
Error message when adding a measure is not seen in new FP

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#131]
Possible related to #132 

See movie of old behavior when trying to add a measure into a FP:

![abc!](https://user-images.githubusercontent.com/29114032/224932564-dbf0cac9-69cb-476e-bb81-9a1c84109233.gif)

See movie of how it works in new FP:

![abc!](https://user-images.githubusercontent.com/29114032/224932859-09b69007-109d-49e5-82f4-16318949a9aa.gif)

`universalModuleDefinition:1 TypeError: propertyHandler.canColorBy is not a function
    at DropMenuBuilder.ColorBy (drop-actions.js:242:1)
    at Object.getDropMeasureOptions (default-extension.js:387:1)
    at default-extension.js:448:1
    at processQueue (angular.js:18075:1)
    at angular.js:18123:1
    at Scope.$digest (angular.js:19242:1)
    at Scope.$apply (angular.js:19630:1)
    at Object.__WEBPACK_DEFAULT_EXPORT__ [as $apply] (apply.js:7:1)
    at Drag._end (drag-and-drop-service.js:348:1)
    at Drag.end (drag-and-drop-service.js:354:1) 'Possibly unhandled rejection: {}'`

**Comment by quanho** [comment]
Fixed by https://github.com/qlik-oss/sn-list-objects/pull/136
