### ISSUE TITLE
v0.19.0 | TypeError: Cannot read properties of undefined (reading 'isEnabled')

### ISSUE THREAD

**Issue by M1CK431** [qlik-oss/sn-list-objects#443]
Thanks to the latest v0.19.0 update, my selections bar crash when clicking on any filter to modify it:
```
TypeError: Cannot read properties of undefined (reading 'isEnabled')
    at K_ (ListBoxPopover.jsx:102:45)
    at Cs (react-dom.production.min.js:160:137)
    at Tu (react-dom.production.min.js:289:337)
    at Ld (react-dom.production.min.js:279:389)
    at kd (react-dom.production.min.js:279:320)
    at Cd (react-dom.production.min.js:279:180)
    at fd (react-dom.production.min.js:270:88)
    at gd (react-dom.production.min.js:272:300)
    at Qa (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273
```

The code responsible of the crash is part of the v0.19.0 update:
![image](https://github.com/qlik-oss/sn-list-objects/assets/31622263/cf8338bc-615b-46a8-b1d0-e50239c76c33)

Could you please fix it?

**Comment by M1CK431** [comment]
I guess @haxxmaxx is the good guy to handle this issue 😉

**Comment by haxxmaxx** [comment]
Hi @M1CK431, yupp looks like we need some sanity checking there. That code change is not in this repo. Are you using stardust or some other nebula.js package?

**Comment by M1CK431** [comment]
I'm using stardust 👍🏼

**Comment by haxxmaxx** [comment]
Ok, then it makes sense. I've opened a new bug in the nebula repo. See above.
Thanks for reporting!

**Comment by M1CK431** [comment]
You are right: downgrading startdust to v5.1.x "solve" the issue. Thanks to pointing me in the right direction 😘
