### ISSUE TITLE
Opening a dimension with expression as title will break the FP

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#59]
See movie:
![abc!](https://user-images.githubusercontent.com/29114032/222058896-8e255be4-b3f8-4b2a-8f12-21fdb7d5e421.gif)

Console error:
`app.971ab3a2d32bcc3164dc.js:2 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BqStringExpression%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (3577.d4eb0d58b075ebc43242.js:2:56251)
    at e (3577.d4eb0d58b075ebc43242.js:2:61250)
    at wo (3577.d4eb0d58b075ebc43242.js:2:72875)
    at xi (3577.d4eb0d58b075ebc43242.js:2:121705)
    at bs (3577.d4eb0d58b075ebc43242.js:2:108876)
    at vs (3577.d4eb0d58b075ebc43242.js:2:108804)
    at gs (3577.d4eb0d58b075ebc43242.js:2:108667)
    at is (3577.d4eb0d58b075ebc43242.js:2:105808)
    at Hl (3577.d4eb0d58b075ebc43242.js:2:46753)
    at ts (3577.d4eb0d58b075ebc43242.js:2:102904)`

**Comment by quanho** [comment]
This should be fixed by https://github.com/qlik-trial/sense-client/pull/23364.
